version: "1.0.0"
services:
  qim:
    container_name: qim
    build: .
    ports:
      - "2017:2017"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      TZ: Asia/Shanghai
    volumes:
      - .:/home/qim
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai

  nginx:
    container_name: nginx
    image: nginx
    ports:
       - 2018:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - .:/home/qim
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qim
