name: docker-beta

on:
  push:
    branches:
      - "beta/*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `beta/1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#beta/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jakeee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # context: ./
          # file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jakeee/qim:${{ env.VERSION }}
