name: docker

on:
  push:
    branches:
      # - "release/*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: jakeee/qim:latest, jakeee/qim:${{ env.VERSION }}
