name: release

on:
  push:
    branches:
      - "release/*.*.*"
      - "pre-release/*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jakeee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # context: ./
          # file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jakeee/qim:latest, jakeee/qim:${{ env.VERSION }}

      - run: curl --url "${{ secrets.BT_WEBHOOK_ACCESS_KEY }}&param=${{ env.VERSION }}"
      - run: curl ${{ secrets.RENDER_DEPLOY_WEBHOOK }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: "change version"
        uses: reedyuk/npm-version@1.1.1
        with:
          version: "${{ env.VERSION }}"
          git-tag-version: "false"

      - name: "change version"
        uses: reedyuk/npm-version@1.1.1
        with:
          version: "${{ env.VERSION }}"
          package: "packages/client/"
          git-tag-version: "false"

      - name: "change version"
        uses: reedyuk/npm-version@1.1.1
        with:
          version: "${{ env.VERSION }}"
          package: "packages/server/"
          git-tag-version: "false"

      - run: |
          git config user.name 'Jake Yu'
          git config user.email 'jake.laoyu@gmail.com'
          git add .
          git commit -m "chore: ${{ env.VERSION }}"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "${{ github.ref }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release/*
          pre_release_branches: pre-release/*
          custom_tag: ${{ env.VERSION }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
